version: '2'
services:
  proxy:
    image: "openrepl/proxy"
    ports:
    - "8007:80"
    links:
    - "runcontainer"
  runcontainer:
    image: "openrepl/runcontainer"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/tmp:/tmp"
