version: '2'
services:
  proxy:
    image: "openrepl/proxy"
    ports:
    - "8007:80"
    links:
    - "runcontainer"
    - "store"
    - "examples"
  runcontainer:
    image: "openrepl/runcontainer"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/tmp:/tmp"
  store:
    image: "openrepl/store"
    command: ["-driver", "dir", "-dir", "/storage"]
    volumes:
    - "/storage"
  examples:
    image: "openrepl/examples"
